### ISSUE TITLE
Implement exposing of ports with memory and properly overload mutable PortNamespace properties

### ISSUE THREAD

**Issue by sphuber** [muhrin/plumpy#54]
Current implementation of exposing ports in `plumpy` does not keep a memory of which ports were actually exposed, after the `exclude` and `include` rules had been taken into account, unlike in `aiida-core`. We should move this functionality to `plumpy` and also improve the overloading of mutable `PortNamespace` properties when absorbing one into another

**Comment by muhrin** [comment]
Implemented in #55
